export const ShopRoute = '/shop'
export const HomeRoute = '/'
export const RegisterRoute='/registration'
export const AuthRoute='/authentication'
export const NewsRoute = '/news'
export const LOCAL_API_URL = 'http://localhost:5000/api'